function out1 = g_dynamics_Linearization_RHS_c(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_C
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2019 01:20:14

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
out1 = [0.0;0.0;0.0;sin(s1).*2.55045e2-s1.*cos(s1).*2.55045e2;sin(s2).*2.02125e2-s2.*cos(s2).*2.02125e2;sin(s3).*1.11475e2-s3.*cos(s3).*1.11475e2];
