function out1 = g_dynamics_JSIM(in1)
%G_DYNAMICS_JSIM
%    OUT1 = G_DYNAMICS_JSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2019 01:20:12

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1-q2;
t3 = cos(t2);
t4 = t3.*(1.65e2./1.6e1);
t5 = q1-q3;
t6 = cos(t5);
t7 = t6.*(9.1e1./1.6e1);
t8 = q2-q3;
t9 = cos(t8);
t10 = t9.*(9.1e1./1.6e1);
out1 = reshape([1.375625e1,t4,t7,t4,3.27e2./3.2e1,t10,t7,t10,7.97e2./1.6e2],[3,3]);
