function J1 = g_InverseKinematics_J1(in1)
%G_INVERSEKINEMATICS_J1
%    J1 = G_INVERSEKINEMATICS_J1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2019 01:20:27

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
J1 = reshape([cos(q1).*4.810536044362292e-1,sin(q1).*(-4.810536044362292e-1),1.0,cos(q2).*3.812384473197782e-1,sin(q2).*(-3.812384473197782e-1),1.0,cos(q3).*2.102587800369686e-1,sin(q3).*(-2.102587800369686e-1),1.0],[3,3]);
