function J2 = g_InverseKinematics_J2(in1,in2)
%G_INVERSEKINEMATICS_J2
%    J2 = G_INVERSEKINEMATICS_J2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2019 01:20:27

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
J2 = reshape([v1.*sin(q1).*(-4.810536044362292e-1),v1.*cos(q1).*(-4.810536044362292e-1),0.0,v2.*sin(q2).*(-3.812384473197782e-1),v2.*cos(q2).*(-3.812384473197782e-1),0.0,v3.*sin(q3).*(-2.102587800369686e-1),v3.*cos(q3).*(-2.102587800369686e-1),0.0],[3,3]);
